<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot_model" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="chassis_width" value="1" />
  <xacro:property name="chassis_length" value="2" />
  <xacro:property name="chassis_height" value="3" />
  <xacro:property name="wheel_radius" value="1" />
  <xacro:property name="wheel_length" value="0.3" />

  <!-- Import your model behavior in Gazebo -->
  <xacro:include filename="$(find rrbot_description)/model/rrbot.gazebo.xacro" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find rrbot_description)/model/materials.xacro" />
  <!-- Define your rrbot model -->
  <xacro:macro name="rrbot" params="parent name *origin">

  <!-- Propagate the name to all elements to make them unique -->
  <joint name="${name}_fixed" type="fixed">
    <insert_block name="origin"/>
    <parent link="${parent}"/>
    <child link="${name}_chassis"/>
  </joint>

  <!-- Body -->
  <link name="${name}_chassis">
    <visual>
      <origin xyz="0 0 ${2 * wheel_radius}" rpy="0 0 0"/>
      <geometry>
	<box size="${chassis_width} ${chassis_length} ${chassis_height}"/>
      </geometry>
      <material name="purple"/>
    </visual>
    <inertial>
      <mass value="5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="1e-6" ixz="1e-6" iyy="1e-6" iyz="1e-6" izz="1e-6" />
    </inertial>
  </link>

  <!-- Wheel Front -->
  <link name="${name}_wheel_1">
    <visual>
      <origin xyz="0 0 0" rpy="0 ${PI / 2} 0"/>
      <geometry>
	<cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="RRBOT/yellow"/>
    </visual>
    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="1e-6" ixz="1e-6" iyy="1e-6" iyz="1e-6" izz="1e-6" />
    </inertial>
  </link>

  <joint name="${name}_joint_1" type="revolute">
    <parent link="${name}_chassis"/>
    <child link="${name}_wheel_1"/>
    <origin xyz="0 ${-0.45 * chassis_length} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="10" velocity="1"/>
  </joint>

  <!-- Wheel Rear 1 -->
  <link name="${name}_wheel_2">
    <visual>
      <origin xyz="${-wheel_length / 2} 0 0" rpy="0 ${PI / 2} 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="RRBOT/green"/>
    </visual>
    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="1e-6" ixz="1e-6" iyy="1e-6" iyz="1e-6" izz="1e-6" />
    </inertial>
  </link>

  <joint name="${name}_joint_2" type="revolute">
    <parent link="${name}_chassis"/>
    <child link="${name}_wheel_2"/>
    <origin xyz="${-chassis_width / 2} ${0.45 * chassis_length} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="10" velocity="1"/>
  </joint>

  <!-- Wheel Rear 2 -->
   <link name="${name}_wheel_3">
    <visual>
      <origin xyz="${wheel_length / 2} 0 0" rpy="0 ${PI / 2} 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="RRBOT/blue"/>
    </visual>
    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="1e-6" ixz="1e-6" iyy="1e-6" iyz="1e-6" izz="1e-6" />
    </inertial>
  </link>

  <joint name="${name}_joint_3" type="revolute">
    <parent link="${name}_chassis"/>
    <child link="${name}_wheel_3"/>
    <origin xyz="${chassis_width / 2} ${0.45 * chassis_length} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="10" velocity="1"/>
  </joint>

 <transmission name="${name}_tran_1">
    <type>transmission_interface/SimpleTransmission</type>
    <robotNamespace>${name}</robotNamespace>
    <joint name="${name}_joint_1">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="${name}_motor_1">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="${name}_tran_2">
    <type>transmission_interface/SimpleTransmission</type>
    <robotNamespace>${name}</robotNamespace>
    <joint name="${name}_joint_2">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="${name}_motor_2">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="${name}_tran_3">
    <type>transmission_interface/SimpleTransmission</type>
    <robotNamespace>${name}</robotNamespace>
    <joint name="${name}_joint_3">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="${name}_motor_3">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- Instance your model behavior in Gazebo keeping the name -->
  <xacro:rrbot_gazebo name="${name}"/>
  </xacro:macro>
</robot>
